services:
  kdc:
    image: kdc:latest
    build:
      context: .
      dockerfile: Dockerfile.kdc
      args:
        - DEFAULT_REALM=EXAMPLE.COM
        - DEFAULT_DOMAIN=example.com
        - KDC_HOSTNAME=kdc.example.com
        - ADMIN_SERVER_HOSTNAME=kdc.example.com
    container_name: kdc
    hostname: kdc.example.com
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config_files/hosts:/etc/hosts:ro
      - /etc/conduit/keys:/etc/conduit/keys
    networks:
      conduit:
        ipv4_address: 192.168.20.2

  # this docker container no longer exists on docker hub
  # ldap:
  #   image: osixia/openldap:1.5.0
  #   restart: unless-stopped
  #   container_name: ldap
  #   ports:
  #     - "1389:389"
  #     - "1636:636"
  #   environment:
  #     - LDAP_BASE_DN=dc=example,dc=com
  #     # - LDAP_CUSTOM_LDIF_DIR=/ldifs
  #     - LDAP_ADMIN_USERNAME=admin
  #     - LDAP_ADMIN_PASSWORD=adminpassword
  #     # - LDAP_USERS=testuser
  #     # - LDAP_PASSWORDS=password
  #     # - BITNAMI_DEBUG=true
  #   networks:
  #     conduit:
  #       ipv4_address: 192.168.20.40
  #   volumes:
  #     - ./config_files/ldifs:/container/service/slapd/assets/config/bootstrap/ldif/custom
  #   command: ["--copy-service"]

  client:
    image: client:latest
    build:
      context: ../../
      dockerfile: examples/docker/Dockerfile.client
      args:
        - DEFAULT_REALM=EXAMPLE.COM
        - DEFAULT_DOMAIN=example.com
        - KDC_HOSTNAME=kdc.example.com
        - ADMIN_SERVER_HOSTNAME=kdc.example.com
    container_name: conduit_client
    hostname: client.example.com
    environment:
      GRPC_GO_LOG_SEVERITY_LEVEL: info
      GRPC_GO_LOG_VERBOSITY_LEVEL: 99
    depends_on:
      - kdc
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config_files/hosts:/etc/hosts:ro
      - ../../:/conduit/conduit
      - ../../../conduit-cli:/conduit/conduit-cli
      - /etc/conduit/keys:/etc/conduit/keys:ro
      - ./config_files/conduit-server-config.yaml:/etc/conduit/conduit-server-config.yaml:ro
      - ./config_files/conduit-cli-config.yaml:/etc/conduit/conduit-cli-config.yaml:ro
      - /etc/conduit/conduit_fs_1:/mnt/fs_1
      - /etc/conduit/conduit_fs_2:/mnt/fs_2
    networks:
      conduit:
        ipv4_address: 192.168.20.4

  conduit-server:
    image: conduit-server:latest
    build:
      context: ../../
      dockerfile: docker/Dockerfile.server
      args:
        - GOVER=1.25
        - ALPINE=3.22
    container_name: conduit-server
    hostname: conduit-server.example.com
    depends_on:
      kdc:
        condition: service_started
        restart: false
      etcd-1:
        condition: service_started
        restart: false
      etcd-2:
        condition: service_started
        restart: false
      etcd-3:
        condition: service_started
        restart: false
      rqlite-1:
        condition: service_started
        restart: false
      rqlite-2:
        condition: service_started
        restart: false
      rqlite-3:
        condition: service_started
        restart: false
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config_files/hosts:/etc/hosts:ro
      - ../../:/conduit/conduit
      - /etc/conduit/keys:/etc/conduit/keys
      - ./config_files/conduit-server-config.yaml:/etc/conduit/conduit-server-config.yaml:ro
    command:
      - -d
      # - --clear-etcd
    stop_grace_period: 3m
    environment:
      # GRPC_GO_LOG_SEVERITY_LEVEL: info
      # GRPC_GO_LOG_VERBOSITY_LEVEL: 99
      CONDUIT_TEST: 1
    networks:
      conduit:
        ipv4_address: 192.168.20.3
      # kind:
      #   ipv4_address: 172.18.0.10

  fta1:
    image: fta:latest
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: fta1
    hostname: fta1.example.com
    restart: unless-stopped
    privileged: true
    cap_add:
      - SYS_ADMIN
    ulimits:
      stack: -1
    shm_size: "1gb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config_files/hosts:/etc/hosts:ro
      - /etc/conduit/keys:/etc/conduit/keys:ro
      - ./config_files/conduit-server-config.yaml:/etc/conduit/conduit-server-config.yaml:ro
      - ./config_files/conduit-fta-config.yaml:/etc/conduit/conduit-fta-config.yaml:ro
      - ./config_files/conduit-runner-config.yaml:/etc/conduit/conduit-runner-config.yaml:ro
      # - /sys/fs/cgroup/system.slice:/sys/fs/cgroup/system.slice
      - /etc/conduit/ssh/testuser:/home/testuser/.ssh:ro
      - /etc/conduit/ssh/host/ssh_host_ecdsa_key:/etc/ssh/ssh_host_ecdsa_key:ro
      - /etc/conduit/ssh/host/ssh_host_ecdsa_key.pub:/etc/ssh/ssh_host_ecdsa_key.pub:ro
      - /etc/conduit/conduit_fs_1:/mnt/fs_1
      - /etc/conduit/conduit_fs_2:/mnt/fs_2
    networks:
      conduit:
        ipv4_address: 192.168.20.6
  fta2:
    image: fta:latest
    container_name: fta2
    hostname: fta2.example.com
    restart: unless-stopped
    privileged: true
    cap_add:
      - SYS_ADMIN
    ulimits:
      stack: -1
    shm_size: "1gb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config_files/hosts:/etc/hosts:ro
      - /etc/conduit/keys:/etc/conduit/keys:ro
      - ./config_files/conduit-server-config.yaml:/etc/conduit/conduit-server-config.yaml:ro
      - ./config_files/conduit-fta-config.yaml:/etc/conduit/conduit-fta-config.yaml:ro
      - ./config_files/conduit-runner-config.yaml:/etc/conduit/conduit-runner-config.yaml:ro
      # - /sys/fs/cgroup/system.slice:/sys/fs/cgroup/system.slice
      - /etc/conduit/ssh/testuser:/home/testuser/.ssh:ro
      - /etc/conduit/ssh/host/ssh_host_ecdsa_key:/etc/ssh/ssh_host_ecdsa_key:ro
      - /etc/conduit/ssh/host/ssh_host_ecdsa_key.pub:/etc/ssh/ssh_host_ecdsa_key.pub:ro
      - /etc/conduit/conduit_fs_1:/mnt/fs_1
      - /etc/conduit/conduit_fs_2:/mnt/fs_2
    networks:
      conduit:
        ipv4_address: 192.168.20.7

  etcd-1:
    image: gcr.io/etcd-development/etcd:v3.6.11
    container_name: etcd-1
    hostname: etcd-1.example.com
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config_files/hosts:/etc/hosts:ro
      - /etc/conduit/keys:/conduit:ro
      - /etc/conduit/etcd-1:/etcd-data
    command:
      - /usr/local/bin/etcd
      - --name=etcd-1
      - --data-dir=/etcd-data
      - --listen-client-urls=https://192.168.20.21:2379
      - --advertise-client-urls=https://192.168.20.21:2379
      - --listen-peer-urls=https://192.168.20.21:2380
      - --initial-advertise-peer-urls=https://192.168.20.21:2380
      - --initial-cluster=etcd-1=https://192.168.20.21:2380,etcd-2=https://192.168.20.22:2380,etcd-3=https://192.168.20.23:2380
      - --initial-cluster-token=token-01
      - --initial-cluster-state=new
      - --log-level=debug
      - --logger=zap
      - --log-outputs=stderr
      - --cert-file=/conduit/etcd-server-cert.pem
      - --key-file=/conduit/etcd-server-key.pem
      - --client-cert-auth
      - --trusted-ca-file=/conduit/conduit-internal-ca.pem
      - --peer-cert-file=/conduit/etcd-server-cert.pem
      - --peer-key-file=/conduit/etcd-server-key.pem
      - --peer-trusted-ca-file=/conduit/conduit-internal-ca.pem
      - --peer-client-cert-auth
      - --quota-backend-bytes=8589934592
    networks:
      conduit:
        ipv4_address: 192.168.20.21
  etcd-2:
    image: gcr.io/etcd-development/etcd:v3.6.11
    container_name: etcd-2
    hostname: etcd-2.example.com
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config_files/hosts:/etc/hosts:ro
      - /etc/conduit/keys:/conduit:ro
      - /etc/conduit/etcd-2:/etcd-data
    command:
      - /usr/local/bin/etcd
      - --name=etcd-2
      - --data-dir=/etcd-data
      - --listen-client-urls=https://192.168.20.22:2379
      - --advertise-client-urls=https://192.168.20.22:2379
      - --listen-peer-urls=https://192.168.20.22:2380
      - --initial-advertise-peer-urls=https://192.168.20.22:2380
      - --initial-cluster=etcd-1=https://192.168.20.21:2380,etcd-2=https://192.168.20.22:2380,etcd-3=https://192.168.20.23:2380
      - --initial-cluster-token=token-01
      - --initial-cluster-state=new
      - --log-level=debug
      - --logger=zap
      - --log-outputs=stderr
      - --cert-file=/conduit/etcd-server-cert.pem
      - --key-file=/conduit/etcd-server-key.pem
      - --client-cert-auth
      - --trusted-ca-file=/conduit/conduit-internal-ca.pem
      - --peer-cert-file=/conduit/etcd-server-cert.pem
      - --peer-key-file=/conduit/etcd-server-key.pem
      - --peer-trusted-ca-file=/conduit/conduit-internal-ca.pem
      - --peer-client-cert-auth
      - --quota-backend-bytes=8589934592
    networks:
      conduit:
        ipv4_address: 192.168.20.22
  etcd-3:
    image: gcr.io/etcd-development/etcd:v3.6.11
    container_name: etcd-3
    hostname: etcd-3.example.com
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config_files/hosts:/etc/hosts:ro
      - /etc/conduit/keys:/conduit:ro
      - /etc/conduit/etcd-3:/etcd-data
    command:
      - /usr/local/bin/etcd
      - --name=etcd-3
      - --data-dir=/etcd-data
      - --listen-client-urls=https://192.168.20.23:2379
      - --advertise-client-urls=https://192.168.20.23:2379
      - --listen-peer-urls=https://192.168.20.23:2380
      - --initial-advertise-peer-urls=https://192.168.20.23:2380
      - --initial-cluster=etcd-1=https://192.168.20.21:2380,etcd-2=https://192.168.20.22:2380,etcd-3=https://192.168.20.23:2380
      - --initial-cluster-token=token-01
      - --initial-cluster-state=new
      - --log-level=debug
      - --logger=zap
      - --log-outputs=stderr
      - --cert-file=/conduit/etcd-server-cert.pem
      - --key-file=/conduit/etcd-server-key.pem
      - --client-cert-auth
      - --trusted-ca-file=/conduit/conduit-internal-ca.pem
      - --peer-cert-file=/conduit/etcd-server-cert.pem
      - --peer-key-file=/conduit/etcd-server-key.pem
      - --peer-trusted-ca-file=/conduit/conduit-internal-ca.pem
      - --peer-client-cert-auth
      - --quota-backend-bytes=8589934592
    networks:
      conduit:
        ipv4_address: 192.168.20.23

  rqlite-1:
    image: rqlite/rqlite:10.1.0
    container_name: rqlite-1
    hostname: rqlite-1.example.com
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config_files/hosts:/etc/hosts:ro
      - /etc/conduit/keys:/conduit:ro
      - /etc/conduit/rqlite-1:/rqlite/file
    command:
      - -node-id=1
      - -http-ca-cert=/conduit/conduit-internal-ca.pem
      - -http-cert=/conduit/rqlite-server-cert.pem
      - -http-key=/conduit/rqlite-server-key.pem
      - -http-verify-client=true
      - -http-addr=192.168.20.31:4001
      - -http-adv-addr=192.168.20.31:4001
      - -raft-addr=192.168.20.31:4002
      - -raft-adv-addr=192.168.20.31:4002
      - -node-cert=/conduit/rqlite-server-cert.pem
      - -node-key=/conduit/rqlite-server-key.pem
      - -node-ca-cert=/conduit/conduit-internal-ca.pem
      - -node-verify-client=true
    networks:
      conduit:
        ipv4_address: 192.168.20.31

  rqlite-2:
    image: rqlite/rqlite:10.1.0
    container_name: rqlite-2
    hostname: rqlite-2.example.com
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config_files/hosts:/etc/hosts:ro
      - /etc/conduit/keys:/conduit:ro
      - /etc/conduit/rqlite-2:/rqlite/file
    command:
      - -node-id=2
      - -http-ca-cert=/conduit/conduit-internal-ca.pem
      - -http-cert=/conduit/rqlite-server-cert.pem
      - -http-key=/conduit/rqlite-server-key.pem
      - -http-verify-client=true
      - -http-addr=192.168.20.32:4001
      - -http-adv-addr=192.168.20.32:4001
      - -raft-addr=192.168.20.32:4002
      - -raft-adv-addr=192.168.20.32:4002
      - -join=192.168.20.31:4002
      - -node-cert=/conduit/rqlite-server-cert.pem
      - -node-key=/conduit/rqlite-server-key.pem
      - -node-ca-cert=/conduit/conduit-internal-ca.pem
      - -node-verify-client=true
    networks:
      conduit:
        ipv4_address: 192.168.20.32

  rqlite-3:
    image: rqlite/rqlite:10.1.0
    container_name: rqlite-3
    hostname: rqlite-3.example.com
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config_files/hosts:/etc/hosts:ro
      - /etc/conduit/keys:/conduit:ro
      - /etc/conduit/rqlite-3:/rqlite/file
    command:
      - -node-id=3
      - -http-ca-cert=/conduit/conduit-internal-ca.pem
      - -http-cert=/conduit/rqlite-server-cert.pem
      - -http-key=/conduit/rqlite-server-key.pem
      - -http-verify-client=true
      - -http-addr=192.168.20.33:4001
      - -http-adv-addr=192.168.20.33:4001
      - -raft-addr=192.168.20.33:4002
      - -raft-adv-addr=192.168.20.33:4002
      - -join=192.168.20.31:4002
      - -node-cert=/conduit/rqlite-server-cert.pem
      - -node-key=/conduit/rqlite-server-key.pem
      - -node-ca-cert=/conduit/conduit-internal-ca.pem
      - -node-verify-client=true
    networks:
      conduit:
        ipv4_address: 192.168.20.33

networks:
  conduit:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24
  # kind:
  #   external: true
