FROM rockylinux:8

RUN dnf install -y epel-release \
    && dnf group install -y "Development Tools" \
    && dnf install -y make wget git sudo gcc autoconf automake m4 libtool mpi openmpi-devel openssl-devel

RUN git clone https://github.com/pftool/pftool.git /pftool \
    && cd /pftool \
    && export PATH=$PATH:/usr/lib64/openmpi/bin/ \
    && autoreconf -i \
    && ./configure --enable-conduit --prefix=/etc/pftool \
    && make install

RUN cp /etc/pftool/etc/example-pftool.cfg /etc/pftool/etc/pftool.cfg \
    && sed -i 's/mpirun: mpirun/mpirun: \/usr\/lib64\/openmpi\/bin\/mpirun/' /etc/pftool/etc/pftool.cfg \
    && sed -i 's/min_per_node: 2/min_per_node: 4/' /etc/pftool/etc/pftool.cfg \
    && sed -i 's/localhost: ON/#localhost:ON\nfta1: ON\nfta2: ON/' /etc/pftool/etc/pftool.cfg
