site_name: CONDUIT
site_description: Documentation for Conduit
site_url: https://lanl.github.io/conduit/
repo_url: https://github.com/lanl/conduit
repo_name: lanl/conduit

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - toc.follow

plugins:
  - search

nav:
  - Overview: index.md
  - Quick Start Guide: quick-start.md
  - Installation: installation.md
  - Architecture: architecture.md
  - User Guide:
      - Conduit CLI: usage/conduit-cli-usage.md
      - Advanced Queries: usage/advanced-query.md
      - Python Client: integrations/python-client.md
  - Operations Guide:
      - Full Reference Config: operations/full-reference-config.md
      - Generating Certificates: operations/cert-generation.md
      - Start & Stop Server: operations/start-stop-server.md
      - Errant Paths: operations/errant-paths.md
      - ETCD Direct Query: operations/etcd-direct-query.md
      - LDAP: operations/ldap.md
      - Slurm Plugin: integrations/slurm-plugin.md
