client:
  grpc-limit: 100000000
  cert: ""
  key: ""
conduit:
  ca: ""
  ip: conduit-server.example.com
  port: 23456
  request-timeout: 5s
debug: false
krb:
  cache: /tmp
  cache-prefix: krb5cc_
  config: /etc/krb5.conf
  spn: conduit/conduit-server.example.com
  kinit-Path: ""
