auth:
  # location of CA Cert used for internal connections to the conduit server API (ex: conduit-runner, conduit-fta, etcd, rqlite use this cert)
  internal-ca-cert: /etc/conduit/conduit-internal-ca.pem
  # location of the paired key for the internal CA cert. Keep this safe
  internal-ca-key: /etc/conduit/conduit-internal-key.pem
# hostname, ip address, and port for the etcd nodes that this conduit instance will attempt to connect to. This will be etcd's `listen-client-urls` value. Hostname is used for mTLS certs
etcd:
  - hostname: etcd.example.com
    ip: 127.0.0.1
    port: 2379
fta:
  # define any extra environment variables that will be sent to the environment that runs conduit-fta
  environment:
    LD_LIBRARY_PATH: /lib/:/lib64/:/usr/local/lib
    PATH: /bin:/usr/bin/:/usr/local/bin/
  # define any flags for conduit-fta
  options:
    - "-d"
  # the path to the conduit-fta binary
  path: conduit-fta
server:
  # list of hostnames that the conduit runner will include in it's server cert. This allows you to use the same cert for multiple conduit runner instances
  hostname:
    - conduitrunner.example.com
  # list of ip addresses that the conduit runner will listen on and include in it's server cert. This allows you to use the same cert for multiple conduit runner instances. If multiple IP addresses are specified, the runner will listen on 0.0.0.0
  ip:
    - 127.0.0.1
  # port that the conduit runner will listen on
  port: 23457
