# Copyright 2026. Triad National Security, LLC. All rights reserved.

### Build Arguments (override via "--build-arg")
ARG GOVER="1.26"
ARG ALPINE="3.22"

################################################################################
### Stage #1:  Alpine-based Go dev env with Conduit built & installed
################################################################################
FROM docker.io/library/golang:${GOVER}-alpine AS conduit-build
LABEL maintainer="Kevin Pelzel <kpelzel@lanl.gov>"

ARG TARGETARCH
ARG TARGETOS

ARG GOARCH="${TARGETARCH}"
ARG GOOS="${TARGETOS}"
WORKDIR "/conduit"
RUN mkdir -p /conduit

RUN apk add --no-cache \
        git

# Copy go.mod and go.sum first for better layer caching
COPY go.mod go.sum ./
RUN go mod download \
    && go install golang.org/x/tools/go/analysis/passes/nilness/cmd/nilness@latest

# Copy the rest of the source code
COPY . .

# run tests
RUN go vet -vettool $(which nilness) ./... \
    && go test ./...

# build conduit
RUN --mount=type=cache,target=/root/.cache/go-build \
    go build -o conduit-server ./cmd/server \
    && cp -v conduit-server /sbin/conduit-server

ENTRYPOINT [ "/sbin/conduit-server" ]
CMD [ "-h" ]

################################################################################
### Stage #2:  Pure Alpine container (no Go) with conduit copied in
################################################################################
FROM docker.io/library/alpine:${ALPINE} AS conduit-server
LABEL maintainer="Kevin Pelzel <kpelzel@lanl.gov>"

ARG TARGETARCH
ARG TARGETOS

RUN mkdir -p /etc/conduit 

RUN wget -q -O /bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/latest/download/grpc_health_probe-${TARGETOS}-${TARGETARCH} && \
    chmod +x /bin/grpc_health_probe

COPY --from=conduit-build /sbin/conduit-server /sbin/conduit-server

ENTRYPOINT [ "/sbin/conduit-server" ]
# CMD [ "--config", "/etc/conduit/config.yaml" ]
