// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConduitApiClient is the client API for ConduitApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConduitApiClient interface {
	// StartTransfer takes in a TransferRequest object and is returned a TransferDetails object with the transfer id
	StartTransfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferDetails, error)
	// StopTransfer takes in a conduit transfer id and is returned a TransferDetails object
	StopTransfer(ctx context.Context, in *TransferIds, opts ...grpc.CallOption) (*MultiTransferDetails, error)
	// Query takes in a query string. If none is provided, it will return details for all transfers for that user
	Query(ctx context.Context, in *QueryOptions, opts ...grpc.CallOption) (*MultiTransferDetails, error)
	// WatchStatus takes in a conduit transfer id. If none is provided, it will return a details stream for all transfers for that user
	WatchStatus(ctx context.Context, in *TransferIds, opts ...grpc.CallOption) (ConduitApi_WatchStatusClient, error)
	// GetCert will authenticate with kerberos and return an mTLS client cert and private key (bundled in a PEM) for that user
	GetCert(ctx context.Context, in *CertRequest, opts ...grpc.CallOption) (*CertResponse, error)
	// Version returns the version info of the conduit server
	Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionInfo, error)
	// PauseTransfer will pause all leases in a transfer at a certain state
	PauseTransfer(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*TransferDetails, error)
	// ValidateTransfer takes in a TransferRequest object and is returned a TransferDetails object with the transfer id. ValidateTransfer will only run validation and will never actually transfer
	ValidateTransfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferDetails, error)
	// ServerControl will shutdown the transfer workers and watchdogs in the conduit server
	ServerControl(ctx context.Context, in *ServerControlRequest, opts ...grpc.CallOption) (*ServerControlResponse, error)
	// SchedulerInfo will return information about the scheduler in conduit
	SchedulerInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SchedulerInfoResponse, error)
	// ErrantPaths will return a list of paths that need to be manually recovered by the user
	ErrantPaths(ctx context.Context, in *ErrantPathsRequest, opts ...grpc.CallOption) (*ErrantPathsResponse, error)
	// PurgeErrantPath will remove an errant path from conduit etcd instance. Returns the paths that were removed
	PurgeErrantPath(ctx context.Context, in *PurgeErrantPathRequest, opts ...grpc.CallOption) (*ErrantPathsResponse, error)
	// TransferNotify is a long running stream that will send a transferid when a new one is created for a user
	TransferNotify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (ConduitApi_TransferNotifyClient, error)
}

type conduitApiClient struct {
	cc grpc.ClientConnInterface
}

func NewConduitApiClient(cc grpc.ClientConnInterface) ConduitApiClient {
	return &conduitApiClient{cc}
}

func (c *conduitApiClient) StartTransfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferDetails, error) {
	out := new(TransferDetails)
	err := c.cc.Invoke(ctx, "/conduitapi.ConduitApi/StartTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conduitApiClient) StopTransfer(ctx context.Context, in *TransferIds, opts ...grpc.CallOption) (*MultiTransferDetails, error) {
	out := new(MultiTransferDetails)
	err := c.cc.Invoke(ctx, "/conduitapi.ConduitApi/StopTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conduitApiClient) Query(ctx context.Context, in *QueryOptions, opts ...grpc.CallOption) (*MultiTransferDetails, error) {
	out := new(MultiTransferDetails)
	err := c.cc.Invoke(ctx, "/conduitapi.ConduitApi/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conduitApiClient) WatchStatus(ctx context.Context, in *TransferIds, opts ...grpc.CallOption) (ConduitApi_WatchStatusClient, error) {
	stream, err := c.cc.NewStream(ctx, &ConduitApi_ServiceDesc.Streams[0], "/conduitapi.ConduitApi/WatchStatus", opts...)
	if err != nil {
		return nil, err
	}
	x := &conduitApiWatchStatusClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ConduitApi_WatchStatusClient interface {
	Recv() (*MultiTransferDetails, error)
	grpc.ClientStream
}

type conduitApiWatchStatusClient struct {
	grpc.ClientStream
}

func (x *conduitApiWatchStatusClient) Recv() (*MultiTransferDetails, error) {
	m := new(MultiTransferDetails)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *conduitApiClient) GetCert(ctx context.Context, in *CertRequest, opts ...grpc.CallOption) (*CertResponse, error) {
	out := new(CertResponse)
	err := c.cc.Invoke(ctx, "/conduitapi.ConduitApi/GetCert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conduitApiClient) Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionInfo, error) {
	out := new(VersionInfo)
	err := c.cc.Invoke(ctx, "/conduitapi.ConduitApi/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conduitApiClient) PauseTransfer(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*TransferDetails, error) {
	out := new(TransferDetails)
	err := c.cc.Invoke(ctx, "/conduitapi.ConduitApi/PauseTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conduitApiClient) ValidateTransfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferDetails, error) {
	out := new(TransferDetails)
	err := c.cc.Invoke(ctx, "/conduitapi.ConduitApi/ValidateTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conduitApiClient) ServerControl(ctx context.Context, in *ServerControlRequest, opts ...grpc.CallOption) (*ServerControlResponse, error) {
	out := new(ServerControlResponse)
	err := c.cc.Invoke(ctx, "/conduitapi.ConduitApi/ServerControl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conduitApiClient) SchedulerInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SchedulerInfoResponse, error) {
	out := new(SchedulerInfoResponse)
	err := c.cc.Invoke(ctx, "/conduitapi.ConduitApi/SchedulerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conduitApiClient) ErrantPaths(ctx context.Context, in *ErrantPathsRequest, opts ...grpc.CallOption) (*ErrantPathsResponse, error) {
	out := new(ErrantPathsResponse)
	err := c.cc.Invoke(ctx, "/conduitapi.ConduitApi/ErrantPaths", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conduitApiClient) PurgeErrantPath(ctx context.Context, in *PurgeErrantPathRequest, opts ...grpc.CallOption) (*ErrantPathsResponse, error) {
	out := new(ErrantPathsResponse)
	err := c.cc.Invoke(ctx, "/conduitapi.ConduitApi/PurgeErrantPath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conduitApiClient) TransferNotify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (ConduitApi_TransferNotifyClient, error) {
	stream, err := c.cc.NewStream(ctx, &ConduitApi_ServiceDesc.Streams[1], "/conduitapi.ConduitApi/TransferNotify", opts...)
	if err != nil {
		return nil, err
	}
	x := &conduitApiTransferNotifyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ConduitApi_TransferNotifyClient interface {
	Recv() (*NotifyMessage, error)
	grpc.ClientStream
}

type conduitApiTransferNotifyClient struct {
	grpc.ClientStream
}

func (x *conduitApiTransferNotifyClient) Recv() (*NotifyMessage, error) {
	m := new(NotifyMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ConduitApiServer is the server API for ConduitApi service.
// All implementations must embed UnimplementedConduitApiServer
// for forward compatibility
type ConduitApiServer interface {
	// StartTransfer takes in a TransferRequest object and is returned a TransferDetails object with the transfer id
	StartTransfer(context.Context, *TransferRequest) (*TransferDetails, error)
	// StopTransfer takes in a conduit transfer id and is returned a TransferDetails object
	StopTransfer(context.Context, *TransferIds) (*MultiTransferDetails, error)
	// Query takes in a query string. If none is provided, it will return details for all transfers for that user
	Query(context.Context, *QueryOptions) (*MultiTransferDetails, error)
	// WatchStatus takes in a conduit transfer id. If none is provided, it will return a details stream for all transfers for that user
	WatchStatus(*TransferIds, ConduitApi_WatchStatusServer) error
	// GetCert will authenticate with kerberos and return an mTLS client cert and private key (bundled in a PEM) for that user
	GetCert(context.Context, *CertRequest) (*CertResponse, error)
	// Version returns the version info of the conduit server
	Version(context.Context, *emptypb.Empty) (*VersionInfo, error)
	// PauseTransfer will pause all leases in a transfer at a certain state
	PauseTransfer(context.Context, *PauseRequest) (*TransferDetails, error)
	// ValidateTransfer takes in a TransferRequest object and is returned a TransferDetails object with the transfer id. ValidateTransfer will only run validation and will never actually transfer
	ValidateTransfer(context.Context, *TransferRequest) (*TransferDetails, error)
	// ServerControl will shutdown the transfer workers and watchdogs in the conduit server
	ServerControl(context.Context, *ServerControlRequest) (*ServerControlResponse, error)
	// SchedulerInfo will return information about the scheduler in conduit
	SchedulerInfo(context.Context, *emptypb.Empty) (*SchedulerInfoResponse, error)
	// ErrantPaths will return a list of paths that need to be manually recovered by the user
	ErrantPaths(context.Context, *ErrantPathsRequest) (*ErrantPathsResponse, error)
	// PurgeErrantPath will remove an errant path from conduit etcd instance. Returns the paths that were removed
	PurgeErrantPath(context.Context, *PurgeErrantPathRequest) (*ErrantPathsResponse, error)
	// TransferNotify is a long running stream that will send a transferid when a new one is created for a user
	TransferNotify(*NotifyRequest, ConduitApi_TransferNotifyServer) error
	mustEmbedUnimplementedConduitApiServer()
}

// UnimplementedConduitApiServer must be embedded to have forward compatible implementations.
type UnimplementedConduitApiServer struct {
}

func (UnimplementedConduitApiServer) StartTransfer(context.Context, *TransferRequest) (*TransferDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartTransfer not implemented")
}
func (UnimplementedConduitApiServer) StopTransfer(context.Context, *TransferIds) (*MultiTransferDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopTransfer not implemented")
}
func (UnimplementedConduitApiServer) Query(context.Context, *QueryOptions) (*MultiTransferDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedConduitApiServer) WatchStatus(*TransferIds, ConduitApi_WatchStatusServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchStatus not implemented")
}
func (UnimplementedConduitApiServer) GetCert(context.Context, *CertRequest) (*CertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCert not implemented")
}
func (UnimplementedConduitApiServer) Version(context.Context, *emptypb.Empty) (*VersionInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedConduitApiServer) PauseTransfer(context.Context, *PauseRequest) (*TransferDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseTransfer not implemented")
}
func (UnimplementedConduitApiServer) ValidateTransfer(context.Context, *TransferRequest) (*TransferDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateTransfer not implemented")
}
func (UnimplementedConduitApiServer) ServerControl(context.Context, *ServerControlRequest) (*ServerControlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServerControl not implemented")
}
func (UnimplementedConduitApiServer) SchedulerInfo(context.Context, *emptypb.Empty) (*SchedulerInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SchedulerInfo not implemented")
}
func (UnimplementedConduitApiServer) ErrantPaths(context.Context, *ErrantPathsRequest) (*ErrantPathsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ErrantPaths not implemented")
}
func (UnimplementedConduitApiServer) PurgeErrantPath(context.Context, *PurgeErrantPathRequest) (*ErrantPathsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurgeErrantPath not implemented")
}
func (UnimplementedConduitApiServer) TransferNotify(*NotifyRequest, ConduitApi_TransferNotifyServer) error {
	return status.Errorf(codes.Unimplemented, "method TransferNotify not implemented")
}
func (UnimplementedConduitApiServer) mustEmbedUnimplementedConduitApiServer() {}

// UnsafeConduitApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConduitApiServer will
// result in compilation errors.
type UnsafeConduitApiServer interface {
	mustEmbedUnimplementedConduitApiServer()
}

func RegisterConduitApiServer(s grpc.ServiceRegistrar, srv ConduitApiServer) {
	s.RegisterService(&ConduitApi_ServiceDesc, srv)
}

func _ConduitApi_StartTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConduitApiServer).StartTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conduitapi.ConduitApi/StartTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConduitApiServer).StartTransfer(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConduitApi_StopTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferIds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConduitApiServer).StopTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conduitapi.ConduitApi/StopTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConduitApiServer).StopTransfer(ctx, req.(*TransferIds))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConduitApi_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConduitApiServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conduitapi.ConduitApi/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConduitApiServer).Query(ctx, req.(*QueryOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConduitApi_WatchStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TransferIds)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConduitApiServer).WatchStatus(m, &conduitApiWatchStatusServer{stream})
}

type ConduitApi_WatchStatusServer interface {
	Send(*MultiTransferDetails) error
	grpc.ServerStream
}

type conduitApiWatchStatusServer struct {
	grpc.ServerStream
}

func (x *conduitApiWatchStatusServer) Send(m *MultiTransferDetails) error {
	return x.ServerStream.SendMsg(m)
}

func _ConduitApi_GetCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConduitApiServer).GetCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conduitapi.ConduitApi/GetCert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConduitApiServer).GetCert(ctx, req.(*CertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConduitApi_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConduitApiServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conduitapi.ConduitApi/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConduitApiServer).Version(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConduitApi_PauseTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConduitApiServer).PauseTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conduitapi.ConduitApi/PauseTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConduitApiServer).PauseTransfer(ctx, req.(*PauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConduitApi_ValidateTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConduitApiServer).ValidateTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conduitapi.ConduitApi/ValidateTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConduitApiServer).ValidateTransfer(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConduitApi_ServerControl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConduitApiServer).ServerControl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conduitapi.ConduitApi/ServerControl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConduitApiServer).ServerControl(ctx, req.(*ServerControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConduitApi_SchedulerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConduitApiServer).SchedulerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conduitapi.ConduitApi/SchedulerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConduitApiServer).SchedulerInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConduitApi_ErrantPaths_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ErrantPathsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConduitApiServer).ErrantPaths(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conduitapi.ConduitApi/ErrantPaths",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConduitApiServer).ErrantPaths(ctx, req.(*ErrantPathsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConduitApi_PurgeErrantPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeErrantPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConduitApiServer).PurgeErrantPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conduitapi.ConduitApi/PurgeErrantPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConduitApiServer).PurgeErrantPath(ctx, req.(*PurgeErrantPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConduitApi_TransferNotify_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NotifyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConduitApiServer).TransferNotify(m, &conduitApiTransferNotifyServer{stream})
}

type ConduitApi_TransferNotifyServer interface {
	Send(*NotifyMessage) error
	grpc.ServerStream
}

type conduitApiTransferNotifyServer struct {
	grpc.ServerStream
}

func (x *conduitApiTransferNotifyServer) Send(m *NotifyMessage) error {
	return x.ServerStream.SendMsg(m)
}

// ConduitApi_ServiceDesc is the grpc.ServiceDesc for ConduitApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConduitApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "conduitapi.ConduitApi",
	HandlerType: (*ConduitApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartTransfer",
			Handler:    _ConduitApi_StartTransfer_Handler,
		},
		{
			MethodName: "StopTransfer",
			Handler:    _ConduitApi_StopTransfer_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _ConduitApi_Query_Handler,
		},
		{
			MethodName: "GetCert",
			Handler:    _ConduitApi_GetCert_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _ConduitApi_Version_Handler,
		},
		{
			MethodName: "PauseTransfer",
			Handler:    _ConduitApi_PauseTransfer_Handler,
		},
		{
			MethodName: "ValidateTransfer",
			Handler:    _ConduitApi_ValidateTransfer_Handler,
		},
		{
			MethodName: "ServerControl",
			Handler:    _ConduitApi_ServerControl_Handler,
		},
		{
			MethodName: "SchedulerInfo",
			Handler:    _ConduitApi_SchedulerInfo_Handler,
		},
		{
			MethodName: "ErrantPaths",
			Handler:    _ConduitApi_ErrantPaths_Handler,
		},
		{
			MethodName: "PurgeErrantPath",
			Handler:    _ConduitApi_PurgeErrantPath_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchStatus",
			Handler:       _ConduitApi_WatchStatus_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TransferNotify",
			Handler:       _ConduitApi_TransferNotify_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}

// ConduitRunnerApiClient is the client API for ConduitRunnerApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConduitRunnerApiClient interface {
	GetNodeStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NodeStatus, error)
	GetNodeStatusStream(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (ConduitRunnerApi_GetNodeStatusStreamClient, error)
	SubmitFTAJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*NodeStatus, error)
}

type conduitRunnerApiClient struct {
	cc grpc.ClientConnInterface
}

func NewConduitRunnerApiClient(cc grpc.ClientConnInterface) ConduitRunnerApiClient {
	return &conduitRunnerApiClient{cc}
}

func (c *conduitRunnerApiClient) GetNodeStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NodeStatus, error) {
	out := new(NodeStatus)
	err := c.cc.Invoke(ctx, "/conduitapi.ConduitRunnerApi/getNodeStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conduitRunnerApiClient) GetNodeStatusStream(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (ConduitRunnerApi_GetNodeStatusStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &ConduitRunnerApi_ServiceDesc.Streams[0], "/conduitapi.ConduitRunnerApi/getNodeStatusStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &conduitRunnerApiGetNodeStatusStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ConduitRunnerApi_GetNodeStatusStreamClient interface {
	Recv() (*NodeStatus, error)
	grpc.ClientStream
}

type conduitRunnerApiGetNodeStatusStreamClient struct {
	grpc.ClientStream
}

func (x *conduitRunnerApiGetNodeStatusStreamClient) Recv() (*NodeStatus, error) {
	m := new(NodeStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *conduitRunnerApiClient) SubmitFTAJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*NodeStatus, error) {
	out := new(NodeStatus)
	err := c.cc.Invoke(ctx, "/conduitapi.ConduitRunnerApi/submitFTAJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConduitRunnerApiServer is the server API for ConduitRunnerApi service.
// All implementations must embed UnimplementedConduitRunnerApiServer
// for forward compatibility
type ConduitRunnerApiServer interface {
	GetNodeStatus(context.Context, *emptypb.Empty) (*NodeStatus, error)
	GetNodeStatusStream(*emptypb.Empty, ConduitRunnerApi_GetNodeStatusStreamServer) error
	SubmitFTAJob(context.Context, *JobRequest) (*NodeStatus, error)
	mustEmbedUnimplementedConduitRunnerApiServer()
}

// UnimplementedConduitRunnerApiServer must be embedded to have forward compatible implementations.
type UnimplementedConduitRunnerApiServer struct {
}

func (UnimplementedConduitRunnerApiServer) GetNodeStatus(context.Context, *emptypb.Empty) (*NodeStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeStatus not implemented")
}
func (UnimplementedConduitRunnerApiServer) GetNodeStatusStream(*emptypb.Empty, ConduitRunnerApi_GetNodeStatusStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetNodeStatusStream not implemented")
}
func (UnimplementedConduitRunnerApiServer) SubmitFTAJob(context.Context, *JobRequest) (*NodeStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitFTAJob not implemented")
}
func (UnimplementedConduitRunnerApiServer) mustEmbedUnimplementedConduitRunnerApiServer() {}

// UnsafeConduitRunnerApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConduitRunnerApiServer will
// result in compilation errors.
type UnsafeConduitRunnerApiServer interface {
	mustEmbedUnimplementedConduitRunnerApiServer()
}

func RegisterConduitRunnerApiServer(s grpc.ServiceRegistrar, srv ConduitRunnerApiServer) {
	s.RegisterService(&ConduitRunnerApi_ServiceDesc, srv)
}

func _ConduitRunnerApi_GetNodeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConduitRunnerApiServer).GetNodeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conduitapi.ConduitRunnerApi/getNodeStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConduitRunnerApiServer).GetNodeStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConduitRunnerApi_GetNodeStatusStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConduitRunnerApiServer).GetNodeStatusStream(m, &conduitRunnerApiGetNodeStatusStreamServer{stream})
}

type ConduitRunnerApi_GetNodeStatusStreamServer interface {
	Send(*NodeStatus) error
	grpc.ServerStream
}

type conduitRunnerApiGetNodeStatusStreamServer struct {
	grpc.ServerStream
}

func (x *conduitRunnerApiGetNodeStatusStreamServer) Send(m *NodeStatus) error {
	return x.ServerStream.SendMsg(m)
}

func _ConduitRunnerApi_SubmitFTAJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConduitRunnerApiServer).SubmitFTAJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conduitapi.ConduitRunnerApi/submitFTAJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConduitRunnerApiServer).SubmitFTAJob(ctx, req.(*JobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConduitRunnerApi_ServiceDesc is the grpc.ServiceDesc for ConduitRunnerApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConduitRunnerApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "conduitapi.ConduitRunnerApi",
	HandlerType: (*ConduitRunnerApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getNodeStatus",
			Handler:    _ConduitRunnerApi_GetNodeStatus_Handler,
		},
		{
			MethodName: "submitFTAJob",
			Handler:    _ConduitRunnerApi_SubmitFTAJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "getNodeStatusStream",
			Handler:       _ConduitRunnerApi_GetNodeStatusStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}

// ConduitFTAApiClient is the client API for ConduitFTAApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConduitFTAApiClient interface {
	// getTransfer returns the transfer associated with this FTA session.
	GetTransfer(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TransferDetails, error)
	// start transitions the current scheduler command from submitted to running and records the scheduler nodes for the command.
	Start(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FTAStartResponse, error)
	// heartbeat indicates that the FTA is still responsive. The runner updates the transfer expiry and returns the current transfer error.
	Heartbeat(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FTAHeartbeatResponse, error)
	// updateStatus updates transfer progress/status information.
	UpdateStatus(ctx context.Context, in *ETCDStatusDetails, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// updateAction atomically changes the transfer action if it still has the expected current value.
	UpdateAction(ctx context.Context, in *FTAActionUpdate, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// complete transitions the current scheduler command from running to complete and persists any stage result data.
	Complete(ctx context.Context, in *FTACompleteRequest, opts ...grpc.CallOption) (*FTACompleteResponse, error)
	// fail records an error generated by the current FTA stage.
	Fail(ctx context.Context, in *FTAFailRequest, opts ...grpc.CallOption) (*FTAFailResponse, error)
}

type conduitFTAApiClient struct {
	cc grpc.ClientConnInterface
}

func NewConduitFTAApiClient(cc grpc.ClientConnInterface) ConduitFTAApiClient {
	return &conduitFTAApiClient{cc}
}

func (c *conduitFTAApiClient) GetTransfer(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TransferDetails, error) {
	out := new(TransferDetails)
	err := c.cc.Invoke(ctx, "/conduitapi.ConduitFTAApi/getTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conduitFTAApiClient) Start(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FTAStartResponse, error) {
	out := new(FTAStartResponse)
	err := c.cc.Invoke(ctx, "/conduitapi.ConduitFTAApi/start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conduitFTAApiClient) Heartbeat(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FTAHeartbeatResponse, error) {
	out := new(FTAHeartbeatResponse)
	err := c.cc.Invoke(ctx, "/conduitapi.ConduitFTAApi/heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conduitFTAApiClient) UpdateStatus(ctx context.Context, in *ETCDStatusDetails, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/conduitapi.ConduitFTAApi/updateStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conduitFTAApiClient) UpdateAction(ctx context.Context, in *FTAActionUpdate, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/conduitapi.ConduitFTAApi/updateAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conduitFTAApiClient) Complete(ctx context.Context, in *FTACompleteRequest, opts ...grpc.CallOption) (*FTACompleteResponse, error) {
	out := new(FTACompleteResponse)
	err := c.cc.Invoke(ctx, "/conduitapi.ConduitFTAApi/complete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conduitFTAApiClient) Fail(ctx context.Context, in *FTAFailRequest, opts ...grpc.CallOption) (*FTAFailResponse, error) {
	out := new(FTAFailResponse)
	err := c.cc.Invoke(ctx, "/conduitapi.ConduitFTAApi/fail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConduitFTAApiServer is the server API for ConduitFTAApi service.
// All implementations must embed UnimplementedConduitFTAApiServer
// for forward compatibility
type ConduitFTAApiServer interface {
	// getTransfer returns the transfer associated with this FTA session.
	GetTransfer(context.Context, *emptypb.Empty) (*TransferDetails, error)
	// start transitions the current scheduler command from submitted to running and records the scheduler nodes for the command.
	Start(context.Context, *emptypb.Empty) (*FTAStartResponse, error)
	// heartbeat indicates that the FTA is still responsive. The runner updates the transfer expiry and returns the current transfer error.
	Heartbeat(context.Context, *emptypb.Empty) (*FTAHeartbeatResponse, error)
	// updateStatus updates transfer progress/status information.
	UpdateStatus(context.Context, *ETCDStatusDetails) (*emptypb.Empty, error)
	// updateAction atomically changes the transfer action if it still has the expected current value.
	UpdateAction(context.Context, *FTAActionUpdate) (*emptypb.Empty, error)
	// complete transitions the current scheduler command from running to complete and persists any stage result data.
	Complete(context.Context, *FTACompleteRequest) (*FTACompleteResponse, error)
	// fail records an error generated by the current FTA stage.
	Fail(context.Context, *FTAFailRequest) (*FTAFailResponse, error)
	mustEmbedUnimplementedConduitFTAApiServer()
}

// UnimplementedConduitFTAApiServer must be embedded to have forward compatible implementations.
type UnimplementedConduitFTAApiServer struct {
}

func (UnimplementedConduitFTAApiServer) GetTransfer(context.Context, *emptypb.Empty) (*TransferDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransfer not implemented")
}
func (UnimplementedConduitFTAApiServer) Start(context.Context, *emptypb.Empty) (*FTAStartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedConduitFTAApiServer) Heartbeat(context.Context, *emptypb.Empty) (*FTAHeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedConduitFTAApiServer) UpdateStatus(context.Context, *ETCDStatusDetails) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (UnimplementedConduitFTAApiServer) UpdateAction(context.Context, *FTAActionUpdate) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAction not implemented")
}
func (UnimplementedConduitFTAApiServer) Complete(context.Context, *FTACompleteRequest) (*FTACompleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Complete not implemented")
}
func (UnimplementedConduitFTAApiServer) Fail(context.Context, *FTAFailRequest) (*FTAFailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fail not implemented")
}
func (UnimplementedConduitFTAApiServer) mustEmbedUnimplementedConduitFTAApiServer() {}

// UnsafeConduitFTAApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConduitFTAApiServer will
// result in compilation errors.
type UnsafeConduitFTAApiServer interface {
	mustEmbedUnimplementedConduitFTAApiServer()
}

func RegisterConduitFTAApiServer(s grpc.ServiceRegistrar, srv ConduitFTAApiServer) {
	s.RegisterService(&ConduitFTAApi_ServiceDesc, srv)
}

func _ConduitFTAApi_GetTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConduitFTAApiServer).GetTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conduitapi.ConduitFTAApi/getTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConduitFTAApiServer).GetTransfer(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConduitFTAApi_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConduitFTAApiServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conduitapi.ConduitFTAApi/start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConduitFTAApiServer).Start(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConduitFTAApi_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConduitFTAApiServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conduitapi.ConduitFTAApi/heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConduitFTAApiServer).Heartbeat(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConduitFTAApi_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ETCDStatusDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConduitFTAApiServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conduitapi.ConduitFTAApi/updateStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConduitFTAApiServer).UpdateStatus(ctx, req.(*ETCDStatusDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConduitFTAApi_UpdateAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FTAActionUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConduitFTAApiServer).UpdateAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conduitapi.ConduitFTAApi/updateAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConduitFTAApiServer).UpdateAction(ctx, req.(*FTAActionUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConduitFTAApi_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FTACompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConduitFTAApiServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conduitapi.ConduitFTAApi/complete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConduitFTAApiServer).Complete(ctx, req.(*FTACompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConduitFTAApi_Fail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FTAFailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConduitFTAApiServer).Fail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conduitapi.ConduitFTAApi/fail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConduitFTAApiServer).Fail(ctx, req.(*FTAFailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConduitFTAApi_ServiceDesc is the grpc.ServiceDesc for ConduitFTAApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConduitFTAApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "conduitapi.ConduitFTAApi",
	HandlerType: (*ConduitFTAApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getTransfer",
			Handler:    _ConduitFTAApi_GetTransfer_Handler,
		},
		{
			MethodName: "start",
			Handler:    _ConduitFTAApi_Start_Handler,
		},
		{
			MethodName: "heartbeat",
			Handler:    _ConduitFTAApi_Heartbeat_Handler,
		},
		{
			MethodName: "updateStatus",
			Handler:    _ConduitFTAApi_UpdateStatus_Handler,
		},
		{
			MethodName: "updateAction",
			Handler:    _ConduitFTAApi_UpdateAction_Handler,
		},
		{
			MethodName: "complete",
			Handler:    _ConduitFTAApi_Complete_Handler,
		},
		{
			MethodName: "fail",
			Handler:    _ConduitFTAApi_Fail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
